export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const ALL_USER = 'ALL_USER';
export const ALL_USER_FAIL = 'ALL_USER_FAIL';

export const POST_ARTIS_SUCCSESS = 'POST_ARTIS_SUCCSESS';
export const POST_ARTIS_FAIL = 'POST_ARTIS_FAIL';
export const GET_ALL_ARTIS = 'GET_ALL_ARTIS';
export const GET_ARTIS_FAIL = 'GET_ARTIS_FAIL';

export const POST_MUSIC_SUCCSESS = 'POST_MUSIC_SUCCESS';
export const POST_MUSIC_FAIL = 'POST_MUSIC_SUCCESS';
export const GET_ALL_MUSIC = 'GET_ALL_MUSIC';
export const GET_MUSIC_FAIL = 'GET_MUSIC_FAIL';

export const POST_PAYMENT_SUCCSESS = 'POST_PAYMENT_SUCCSESS';
export const POST_PAYMENT_FAIL = 'POST_PAYMENT_FAIL';
export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS';
export const GET_ALL_TRANSACTION_FAIL = 'GET_ALL_TRANSACTION_FAIL';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_FAIL = 'EDIT_TRANSACTION_FAIL';

export const GET_ONE_MUSIC_SUCCESS = 'GET_ONE_MUSIC_SUCCESS';
export const GET_ONE_MUSIC_FAIL = 'GET_ONE_MUSIC_FAIL';

export const EDIT_UNSUBS_SUCCESS = "EDIT_UNSUBS_SUCCESS";
export const EDIT_UNSUBS_FAIL = "EDIT_UNSUBS_FAIL";
